Version fields for inner repositories are now set properly.
rockerhieu/Versionberg pull request #3
Opened 2018-01-31 09:30 UTC by cengizkandemir

This pull request addresses the Issue #2.

Implementation:
- Set the static project path field of "Git" using project.projectDir.absolutePath.
- Run a dummy git command using the supplied path. Run the original git commands on failure to find the git repository.

2018-01-31 09:42 UTC, rockerhieu commented
I would prefer to add a new attribute `gitDir` for `versionberg`, e.g:

```groovy
versionberg {
    major 1
    minor 0
    gitDir $projectDir // then use this value for the git command
}
```

I think this approach will be more flexible and give the developers full controls on choosing which git repo they want to use to manage the version.

2018-01-31 12:09 UTC, cengizkandemir commented
I've added "gitDir" field. Setting it as

`gitDir "${project.projectDir.absolutePath}/.."`

did the trick. Can you please review the commit?

2018-01-31 17:35 UTC, rockerhieu requested changes
Using `checkInnerGitRepo` method is unnecessary. If `gitDir` is undefined, assign the root project git directory into it, then always use `gitDir` in all git commands.

Avoid using static variables, i.e `getCommitSha(gitDir)` and `getCommitCount(gitDir)` are more preferable.

2018-01-31 17:35 UTC, rockerhieu commented on versionberg/src/main/groovy/io/github/rockerhieu/versionberg/Git.groovy
> +            def externalPathOption = checkInnerGitRepo() ? "--git-dir=${repositoryPath}/.git" : ''
`checkInnerGitRepo` is unnecessary as `getCommitSha` can just accept `gitDir` as a parameter

2018-01-31 17:35 UTC, rockerhieu commented on versionberg/src/main/groovy/io/github/rockerhieu/versionberg/Git.groovy
> +            def externalPathOption = checkInnerGitRepo() ? "--git-dir=${repositoryPath}/.git" : ''
To be clear, here you can always use `gitDir` in the git command.

2018-01-31 17:35 UTC, rockerhieu commented on versionberg/src/main/groovy/io/github/rockerhieu/versionberg/Git.groovy
> +    static String repositoryPath = ''
I think we should avoid using static stateful variable. How about `getCommitSha(gitDir)` and `getCommitCount(gitDir)`?

2018-01-31 17:35 UTC, rockerhieu commented on versionberg/src/main/groovy/io/github/rockerhieu/versionberg/Git.groovy
> +    private static boolean checkInnerGitRepo() {
Using this method is unnecessary. If `gitDir` is undefined, assign the root project git directory into it, then always use `gitDir` in all git commands.

2018-01-31 18:33 UTC, cengizkandemir commented
That was my initial plan but had some problems making it work. I will try to refactor tomorrow.

2018-02-01 07:00 UTC, cengizkandemir commented
I've made the necessary changes. There was a problem with printing version information too early, that is, printing before the gitDir field is set in some subproject. It prints the hash and commit count in root directory. I solved it by printing after evaluation. Not sure if that's best hook, however.

2018-02-01 08:04 UTC, rockerhieu approved these changes

2018-02-01 08:05 UTC, rockerhieu commented
Looking good, I will do a final test in the next couple hours and let you know.

2018-02-01 09:56 UTC, merged

2018-02-01 09:56 UTC, rockerhieu commented
I will do some more improvements on my end, then I will publish a new version soon. Thanks for your contribution @cengizkandemir.

2018-02-01 11:40 UTC, cengizkandemir commented
Thanks. I think you can also close the Issue #2 .

2018-02-01 18:14 UTC, rockerhieu commented
Available in v1.0.1